//
// Created by Thoh Testarossa on 2019-07-19.
//

#ifndef GRAPH_ALGO_ABSTRACTGRAPH_H
#define GRAPH_ALGO_ABSTRACTGRAPH_H

#include "../include/deps.h"

#define INVALID_INITV_INDEX -1

class Vertex
{
public:
    Vertex();
    Vertex(int vertexID, bool activeness, int initVIndex);

    int vertexID;
    bool isActive;
    int initVIndex;
    int outDegree;
    int inDegree;
};

class Edge
{
public:
    Edge();
    Edge(int src, int dst, double weight);

    int src;
    int dst;
    double weight;

    //the origin index in eSet (before divided) = index of message generated by this edge in mValues
    int originIndex;
};

class AbstractGraph
{
public:
    AbstractGraph(int vCount);
    AbstractGraph(const std::vector<Vertex> &vSet, const std::vector<Edge> &eSet);
    AbstractGraph(int vCount, int eCount, int *eSrcSet, int *eDstSet, double *eWeightSet);

    void insertEdge(int src, int dst, double weight);
    void insertEdgeUpdateInfo(int src, int dst, double weight, int originIndex);

    int vCount;
    int eCount;

    std::vector<Vertex> vList;
    std::vector<Edge> eList;
};

#endif //GRAPH_ALGO_ABSTRACTGRAPH_H
